# Generated by Django 5.0.4 on 2024-05-16 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
